
on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add gradle.kts
        run: |
          cat > plain.gradle.kts << EOM
          plugins {
              `java-library`
          }

          repositories {
              jcenter()
              maven {
                  name = "remote"
                  url = uri("https://maven.pkg.github.com/${{ github.repository_owner }}/maven-publish")
                  credentials {
                      username = System.getenv("USERNAME")
                      password = System.getenv("TOKEN")
                  }
              }
          }

          group = "org.test.consume"
          version = "1.0-SNAPSHOT"

          dependencies {
              api("org.apache.commons:commons-math3:3.6.1")
              implementation("com.google.guava:guava:28.0-jre")
              testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.1")
              testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.5.1")
              compile("org.test.plain:publish-java:1.0-SNAPSHOT")
          }

          val test by tasks.getting(Test::class) {
              useJUnitPlatform()
          }
          EOM

      - run: gradle build -b plain.gradle.kts
        env:
          USERNAME: token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
